In [1]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
def getHTML(u):
    try:
        r = requests.get(u,timeout=30)
        r.raise_for_status()
        r.encoding = r.apparent_encoding
        return r.text
    except:
        return 

def getContent(u):
    html = getHTML(u)
    soup = BeautifulSoup(html,'html.parser')
    title = soup.select('div.mbtitle')
    paras_tmp = soup.select('p')
    paras = paras_tmp[3:]
    return paras
 
def saveFile(text):
    f=open('try.txt','w',encoding='utf-8')
    for t in text:
        if len(t) > 0:
            f.writelines(t.get_text() + "\n")
    f.close()
    
def finish(u):
    text = getContent(u)
    saveFile(text)
    
def web(u):
    headers = {
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36'
    }
    url = u
    res = requests.get(url, headers=headers)
    res.encoding='gbk'
    soup = BeautifulSoup(res.text, 'lxml')

    news_list = soup.find('div', {'class': 'pages_content'})
    if news_list==None:
        for x in ['wrap','zw-con']:
            news_list = soup.find('div', {'class': x})
            if news_list!=None:
                break
    news = news_list.find_all('p')

    txt=open('try.txt','w')
    for x in news:
        a=x.text
        txt.write(a)

In [2]:
def ff_lst():
        import requests
        from bs4 import BeautifulSoup
        import jieba
        import requests
        df = pd.read_excel(r'C:\Users\HONEYMOON\Desktop\中央创业政策3.xlsx')
        web = df['网址']
        web_lst = []
        for w in web:
            web_lst.append(w)
        lst = []
        dics_counts={}
        for u in web_lst[260:275]:
            #print(web_lst.index(u)+2)
            try:
                web(u)
            except:
                try:
                    finish(u)
                except:
                    pass
            txt = open('try.txt',encoding = 'utf-8').read()
            #加载停用词表
            stopwords = [line.strip() for line in open(r"D:\try\停用词.txt",encoding="utf-8").readlines()]
            words  = jieba.lcut(txt)
            if len(words) < 10:
                continue
            counts = {}
            lst_top3=[]
            for word in words:
            #不在停用词表中
                if word not in stopwords:
                #不统计字数为一的词
                    if len(word) == 1:
                        continue
                    else:
                        counts[word] = counts.get(word,0) + 1
            items = list(counts.items())
            items.sort(key=lambda x:x[1], reverse=True)
            for i in range(3):
                word, count = items[i]
                if word.isdigit():
                    continue
                else:
                    dics_counts[word]=dics_counts.get(word,0)+1
                    lst_top3.append(word)
            lst.append(lst_top3)
            dics_counts = dict(sorted(dics_counts.items(), key=lambda item:item[1], reverse=True))
        print(dics_counts)
        print(lst)
        return lst
        '''print(lst_top3)
            print(counts)
            print(items)
            print()'''
    

In [3]:
seg_r = ff_lst()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\HONEYM~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.664 seconds.
Prefix dict has been built successfully.


{'青年': 6, '创业': 3, '农村': 3, '团委': 2, '培训': 2, '资金': 1, '评选': 1, '见习': 1, '基地': 1, '职业培训': 1, '就业': 1, '候选人': 1, '竞赛': 1, '全国': 1, '作品': 1, '小额贷款': 1, '登录': 1, '大学生': 1, '计划': 1, '考评': 1, '创建': 1, '贷款': 1, '农民工': 1, '企业': 1, '科技': 1, '创新': 1, '城市': 1, '创新型': 1}
[['资金', '青年', '团委'], ['青年', '创业', '评选'], ['见习', '基地', '青年'], ['培训', '职业培训', '就业'], ['农村', '候选人', '青年'], ['竞赛', '全国', '作品'], ['小额贷款', '登录', '团委'], ['创业', '大学生', '计划'], ['创业', '考评', '创建'], ['青年', '农村', '贷款'], ['培训', '农民工', '企业'], ['科技', '农村', '青年'], ['创新', '城市', '创新型']]


In [4]:
def ff_dic():
        import requests
        from bs4 import BeautifulSoup
        import jieba
        import requests
        df = pd.read_excel(r'C:\Users\HONEYMOON\Desktop\中央创业政策3.xlsx')
        web = df['网址']
        web_lst = []
        for w in web:
            web_lst.append(w)
        lst = []
        dics_counts={}
        for u in web_lst[260:275]:
            #print(web_lst.index(u)+2)
            try:
                web(u)
            except:
                try:
                    finish(u)
                except:
                    pass
            txt = open('try.txt',encoding = 'utf-8').read()
            #加载停用词表
            stopwords = [line.strip() for line in open(r"D:\try\停用词.txt",encoding="utf-8").readlines()]
            words  = jieba.lcut(txt)
            if len(words) < 10:
                continue
            counts = {}
            lst_top3=[]
            for word in words:
            #不在停用词表中
                if word not in stopwords:
                #不统计字数为一的词
                    if len(word) == 1:
                        continue
                    else:
                        counts[word] = counts.get(word,0) + 1
            items = list(counts.items())
            items.sort(key=lambda x:x[1], reverse=True)
            for i in range(3):
                word, count = items[i]
                if word.isdigit():
                    continue
                else:
                    dics_counts[word]=dics_counts.get(word,0)+1
                    lst_top3.append(word)
            lst.append(lst_top3)
            dics_counts = dict(sorted(dics_counts.items(), key=lambda item:item[1], reverse=True))
        return dics_counts
        '''print(lst_top3)
            print(counts)
            print(items)
            print()'''


In [5]:
seg_dic = ff_dic()

In [6]:
for k in list(seg_dic.keys()):   #对字典a中的keys，相当于形成列表list
    if seg_dic[k] < 2:
        del seg_dic[k]
print(seg_dic)

{'青年': 6, '创业': 3, '农村': 3, '团委': 2, '培训': 2}


In [7]:
import os
import jieba
import collections
import numpy as np
from collections import Counter

class Coword_matrix(object):    
    #定义了一个共词矩阵的类  初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
    def __init__(self,Fulltext_cut_content):    
    #传入切词后的嵌套列表，可以得到self.Fulltext_cut_content，self.Full_Feature_word, self.Common_matrix
        '''self.Fulltext_cut_content_str = [" ".join(i) for i in self.Fulltext_cut_content]    
        也可以将列表转化为字符串，使后面对全文本的遍历更快，for...in... 遍历str比遍历list更快！'''
        self.Fulltext_cut_content=Fulltext_cut_content
        Full_familiar_Feature = seg_dic
            # 化为Counter后 作并集，再将结果化为dict
        self.Full_Feature_word,self.Full_Feature_weight= list(Full_familiar_Feature.keys()), list(Full_familiar_Feature.values())

        self.Common_matrix = np.empty((len(self.Full_Feature_word), len(self.Full_Feature_word)))  
        # 构建共词矩阵，大小为[词数]x[词数]
        for row in range(len(self.Full_Feature_word)):  
            # 将共词矩阵 对角线上元素=它自身在所有文章出现次数
            for column in range(len(self.Full_Feature_word)):
                if column == row:
                    self.Common_matrix[row][column] = int(self.Full_Feature_weight[row])
        for i in range(len(self.Full_Feature_word)):  # i的范围为 1 到 词数
            for n in range(1, len(self.Full_Feature_word) - i):  # n的范围为 1到（词数-i）   i+n的范围为 i 到 词数
                word1 = self.Full_Feature_word[i]
                word2 = self.Full_Feature_word[i + n]
                Common_weight = 0
                for Single_Text_Cut in self.Fulltext_cut_content:  
                #遍历每一篇文章的切词结果，如果word1和word2在同一片文章中出现，则该两词的权重+1
                #也可以将Fulltext_cut_content化为字符串后进行遍历，这样更快！
                    '''如果希望统计word1和word2在同一片文章中出现的最小次数，则可以使用 str.count(),
                    或者 list.Counter分别计算次数，再取最小值 赋予权重'''
                    if ((word1 in Single_Text_Cut) and (word2 in Single_Text_Cut)):
                        Common_weight += 1
                self.Common_matrix[i][i + n] = Common_weight    #该矩阵为对角矩阵
                self.Common_matrix[i + n][i] = Common_weight

    def get_Full_Feature_word(self):    #返回特征词列表
        return self.Full_Feature_word

    def get_Common_matrix(self):    #返回共词矩阵
        for j in self.Common_matrix:
            print(j)
        #return self.Common_matrix

    def return_word_row(self,word):    #定义一个方法 参数为一个词，函数返回 该词对应的共词矩阵的那一行
        if word not in self.Full_Feature_word:
            print(word + "   该词不在特征词中！")
        else:
            for row in range(len(self.Full_Feature_word)):
                if word == self.Full_Feature_word[row]:
                    return self.Common_matrix[row]
                

                
                '''
                self.Fulltext_cut_content   初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
                Full_familiar_Feature = {}  # 储存特征和权重，为dict格式
                self.Full_Feature_word  特征词列表
                self.Common_matrix 共词矩阵
                '''

In [8]:
if __name__=="__main__":
    Fulltext_cut_content=seg_r
    Coword_one=Coword_matrix(Fulltext_cut_content) #对该类传入初始化参数
    print('=========================特征词===========================')
    print(Coword_one.get_Full_Feature_word())
    print('========================共词矩阵===========================')
    print(Coword_one.get_Common_matrix())
    print('===============“创业”词与所有特征词的关系程度===============')
    print(Coword_one.return_word_row("创业"))

=========================特征词===========================
['青年', '创业', '农村', '团委', '培训']
========================共词矩阵===========================
[6. 1. 3. 1. 0.]
[1. 3. 0. 0. 0.]
[3. 0. 3. 0. 0.]
[1. 0. 0. 2. 0.]
[0. 0. 0. 0. 2.]
None
===============“创业”词与所有特征词的关系程度===============
[1. 3. 0. 0. 0.]


In [53]:
import os
import jieba
import collections
import numpy as np
from collections import Counter
import xlrd
import xlwt
from xlwt import *

class Coword_matrix(object):    
    #定义了一个共词矩阵的类  初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
    def __init__(self,Fulltext_cut_content):    
    #传入切词后的嵌套列表，可以得到self.Fulltext_cut_content，self.Full_Feature_word, self.Common_matrix
        '''self.Fulltext_cut_content_str = [" ".join(i) for i in self.Fulltext_cut_content]    
        也可以将列表转化为字符串，使后面对全文本的遍历更快，for...in... 遍历str比遍历list更快！'''
        self.Fulltext_cut_content=Fulltext_cut_content
        Full_familiar_Feature = seg_dic
            # 化为Counter后 作并集，再将结果化为dict
        self.Full_Feature_word,self.Full_Feature_weight= list(Full_familiar_Feature.keys()), list(Full_familiar_Feature.values())

        self.Common_matrix = np.empty((len(self.Full_Feature_word), len(self.Full_Feature_word)))  
        # 构建共词矩阵，大小为[词数]x[词数]
        for row in range(len(self.Full_Feature_word)):  
            # 将共词矩阵 对角线上元素=它自身在所有文章出现次数
            for column in range(len(self.Full_Feature_word)):
                if column == row:
                    self.Common_matrix[row][column] = int(self.Full_Feature_weight[row])
        for i in range(len(self.Full_Feature_word)):  # i的范围为 1 到 词数
            for n in range(1, len(self.Full_Feature_word) - i):  # n的范围为 1到（词数-i）   i+n的范围为 i 到 词数
                word1 = self.Full_Feature_word[i]
                word2 = self.Full_Feature_word[i + n]
                Common_weight = 0
                for Single_Text_Cut in self.Fulltext_cut_content:  
                #遍历每一篇文章的切词结果，如果word1和word2在同一片文章中出现，则该两词的权重+1
                #也可以将Fulltext_cut_content化为字符串后进行遍历，这样更快！
                    '''如果希望统计word1和word2在同一片文章中出现的最小次数，则可以使用 str.count(),
                    或者 list.Counter分别计算次数，再取最小值 赋予权重'''
                    if ((word1 in Single_Text_Cut) and (word2 in Single_Text_Cut)):
                        Common_weight += 1
                self.Common_matrix[i][i + n] = Common_weight    #该矩阵为对角矩阵
                self.Common_matrix[i + n][i] = Common_weight

    def get_Full_Feature_word(self):    #返回特征词列表
        return self.Full_Feature_word



    def data_write(self,file_path, datas, i):#datas是列表
        print("datas；",datas)
        print()
        f = xlwt.Workbook()
        sheet1 = f.add_sheet(u'sheet1', cell_overwrite_ok=True)  # 创建sheet
        # 将数据写入第 i 行，第 k 列
        for data in datas:
            for k in range(len(datas)):
                sheet1.write(i, k, datas[k])
        f.save(file_path)  # 保存文件


    
    def get_Common_matrix(self):  #返回共词矩阵
        i = 0
        for j in self.Common_matrix:
            print(j)
            Coword_one.data_write("4.xls", j, i)
            i += 1
        #return self.Common_matrix

    def return_word_row(self,word):    #定义一个方法 参数为一个词，函数返回 该词对应的共词矩阵的那一行
        if word not in self.Full_Feature_word:
            print(word + "   该词不在特征词中！")
        else:
            for row in range(len(self.Full_Feature_word)):
                if word == self.Full_Feature_word[row]:
                    return self.Common_matrix[row]
                

                
                '''
                self.Fulltext_cut_content   初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
                Full_familiar_Feature = {}  # 储存特征和权重，为dict格式
                self.Full_Feature_word  特征词列表
                self.Common_matrix 共词矩阵
                '''

In [55]:
if __name__=="__main__":
    Fulltext_cut_content=seg_r
    Coword_one=Coword_matrix(Fulltext_cut_content) #对该类传入初始化参数
    print('=========================特征词===========================')
    print(Coword_one.get_Full_Feature_word())
    print('========================共词矩阵===========================')
    print(Coword_one.get_Common_matrix())
    print('===============“创业”词与所有特征词的关系程度===============')
    print(Coword_one.return_word_row("创业"))

=========================特征词===========================
['青年', '创业', '农村', '团委', '培训']
========================共词矩阵===========================
[6. 1. 3. 1. 0.]
datas； [6. 1. 3. 1. 0.]

[1. 3. 0. 0. 0.]
datas； [1. 3. 0. 0. 0.]

[3. 0. 3. 0. 0.]
datas； [3. 0. 3. 0. 0.]

[1. 0. 0. 2. 0.]
datas； [1. 0. 0. 2. 0.]

[0. 0. 0. 0. 2.]
datas； [0. 0. 0. 0. 2.]

None
===============“创业”词与所有特征词的关系程度===============
[1. 3. 0. 0. 0.]


In [84]:
import os
import jieba
import collections
import numpy as np
from collections import Counter
import xlrd
import xlwt
from xlwt import *

class Coword_matrix(object):    
    #定义了一个共词矩阵的类  初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
    def __init__(self,Fulltext_cut_content):    
    #传入切词后的嵌套列表，可以得到self.Fulltext_cut_content，self.Full_Feature_word, self.Common_matrix
        '''self.Fulltext_cut_content_str = [" ".join(i) for i in self.Fulltext_cut_content]    
        也可以将列表转化为字符串，使后面对全文本的遍历更快，for...in... 遍历str比遍历list更快！'''
        self.Fulltext_cut_content=Fulltext_cut_content
        Full_familiar_Feature = seg_dic
            # 化为Counter后 作并集，再将结果化为dict
        self.Full_Feature_word,self.Full_Feature_weight= list(Full_familiar_Feature.keys()), list(Full_familiar_Feature.values())

        self.Common_matrix = np.empty((len(self.Full_Feature_word), len(self.Full_Feature_word)))  
        # 构建共词矩阵，大小为[词数]x[词数]
        for row in range(len(self.Full_Feature_word)):  
            # 将共词矩阵 对角线上元素=它自身在所有文章出现次数
            for column in range(len(self.Full_Feature_word)):
                if column == row:
                    self.Common_matrix[row][column] = int(self.Full_Feature_weight[row])
        for i in range(len(self.Full_Feature_word)):  # i的范围为 1 到 词数
            for n in range(1, len(self.Full_Feature_word) - i):  # n的范围为 1到（词数-i）   i+n的范围为 i 到 词数
                word1 = self.Full_Feature_word[i]
                word2 = self.Full_Feature_word[i + n]
                Common_weight = 0
                for Single_Text_Cut in self.Fulltext_cut_content:  
                #遍历每一篇文章的切词结果，如果word1和word2在同一片文章中出现，则该两词的权重+1
                #也可以将Fulltext_cut_content化为字符串后进行遍历，这样更快！
                    '''如果希望统计word1和word2在同一片文章中出现的最小次数，则可以使用 str.count(),
                    或者 list.Counter分别计算次数，再取最小值 赋予权重'''
                    if ((word1 in Single_Text_Cut) and (word2 in Single_Text_Cut)):
                        Common_weight += 1
                self.Common_matrix[i][i + n] = Common_weight    #该矩阵为对角矩阵
                self.Common_matrix[i + n][i] = Common_weight

    def get_Full_Feature_word(self):    #返回特征词列表
        return self.Full_Feature_word



    def data_write(self,file_path, datas, i):#datas是列表
        print("datas；",datas)
        print()
        f = xlwt.Workbook()
        sheet1 = f.add_sheet(u'sheet1', cell_overwrite_ok=True)  # 创建sheet
        # 将数据写入第 i 行，第 k 列
        for data in datas:
            for k in range(len(datas)):
                sheet1.write(i, k+1, datas[k])
        f.save(file_path)  # 保存文件


    
    def get_Common_matrix(self):  #返回共词矩阵
        i = 1
        f = xlwt.Workbook()
        sheet1 = f.add_sheet(u'sheet1', cell_overwrite_ok=True)  # 创建sheet
        for j in self.Common_matrix:
            print(j)
            # 将数据写入第 i 行，第 k 列
            for data in j:
                for k in range(len(j)):
                    sheet1.write(i, k+1, j[k])
            f.save("4.xls")  # 保存文件
            i += 1
        #return self.Common_matrix

    def return_word_row(self,word):    #定义一个方法 参数为一个词，函数返回 该词对应的共词矩阵的那一行
        if word not in self.Full_Feature_word:
            print(word + "   该词不在特征词中！")
        else:
            for row in range(len(self.Full_Feature_word)):
                if word == self.Full_Feature_word[row]:
                    return self.Common_matrix[row]
                

                
                '''
                self.Fulltext_cut_content   初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
                Full_familiar_Feature = {}  # 储存特征和权重，为dict格式
                self.Full_Feature_word  特征词列表
                self.Common_matrix 共词矩阵
                '''

In [85]:
if __name__=="__main__":
    Fulltext_cut_content=seg_r
    Coword_one=Coword_matrix(Fulltext_cut_content) #对该类传入初始化参数
    print('=========================特征词===========================')
    print(Coword_one.get_Full_Feature_word())
    print('========================共词矩阵===========================')
    print(Coword_one.get_Common_matrix())
    print('===============“创业”词与所有特征词的关系程度===============')
    print(Coword_one.return_word_row("创业"))

=========================特征词===========================
['青年', '创业', '农村', '团委', '培训']
========================共词矩阵===========================
[6. 1. 3. 1. 0.]
[1. 3. 0. 0. 0.]
[3. 0. 3. 0. 0.]
[1. 0. 0. 2. 0.]
[0. 0. 0. 0. 2.]
None
===============“创业”词与所有特征词的关系程度===============
[1. 3. 0. 0. 0.]


In [98]:
import os
import jieba
import collections
import numpy as np
from collections import Counter
import xlrd
import xlwt
from xlwt import *

class Coword_matrix(object):    
    #定义了一个共词矩阵的类  初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
    def __init__(self,Fulltext_cut_content):    
    #传入切词后的嵌套列表，可以得到self.Fulltext_cut_content，self.Full_Feature_word, self.Common_matrix
        '''self.Fulltext_cut_content_str = [" ".join(i) for i in self.Fulltext_cut_content]    
        也可以将列表转化为字符串，使后面对全文本的遍历更快，for...in... 遍历str比遍历list更快！'''
        self.Fulltext_cut_content=Fulltext_cut_content
        Full_familiar_Feature = seg_dic
            # 化为Counter后 作并集，再将结果化为dict
        self.Full_Feature_word,self.Full_Feature_weight= list(Full_familiar_Feature.keys()), list(Full_familiar_Feature.values())

        self.Common_matrix = np.empty((len(self.Full_Feature_word), len(self.Full_Feature_word)))  
        # 构建共词矩阵，大小为[词数]x[词数]
        for row in range(len(self.Full_Feature_word)):  
            # 将共词矩阵 对角线上元素=它自身在所有文章出现次数
            for column in range(len(self.Full_Feature_word)):
                if column == row:
                    self.Common_matrix[row][column] = int(self.Full_Feature_weight[row])
        for i in range(len(self.Full_Feature_word)):  # i的范围为 1 到 词数
            for n in range(1, len(self.Full_Feature_word) - i):  # n的范围为 1到（词数-i）   i+n的范围为 i 到 词数
                word1 = self.Full_Feature_word[i]
                word2 = self.Full_Feature_word[i + n]
                Common_weight = 0
                for Single_Text_Cut in self.Fulltext_cut_content:  
                #遍历每一篇文章的切词结果，如果word1和word2在同一片文章中出现，则该两词的权重+1
                #也可以将Fulltext_cut_content化为字符串后进行遍历，这样更快！
                    '''如果希望统计word1和word2在同一片文章中出现的最小次数，则可以使用 str.count(),
                    或者 list.Counter分别计算次数，再取最小值 赋予权重'''
                    if ((word1 in Single_Text_Cut) and (word2 in Single_Text_Cut)):
                        Common_weight += 1
                self.Common_matrix[i][i + n] = Common_weight    #该矩阵为对角矩阵
                self.Common_matrix[i + n][i] = Common_weight

    def get_Full_Feature_word(self):    #返回特征词列表
        return self.Full_Feature_word

    
    def get_Common_matrix(self):  #返回共词矩阵
        full_Feature_word = Coword_one.get_Full_Feature_word()
        f = xlwt.Workbook()
        sheet1 = f.add_sheet(u'sheet1', cell_overwrite_ok=True)  # 创建sheet
        
        for m in full_Feature_word:
            for n in range(len(full_Feature_word)):
                sheet1.write(0, n+1, full_Feature_word[n])
                sheet1.write(n+1, 0, full_Feature_word[n])
        
        i = 1
        for j in self.Common_matrix:
            print(j)
            # 将数据写入第 i 行，第 k+1 列
            for data in j:
                for k in range(len(j)):
                    sheet1.write(i, k+1, j[k])
            f.save("4.xls")  # 保存文件
            i += 1
        #return self.Common_matrix

    def return_word_row(self,word):    #定义一个方法 参数为一个词，函数返回 该词对应的共词矩阵的那一行
        if word not in self.Full_Feature_word:
            print(word + "   该词不在特征词中！")
        else:
            for row in range(len(self.Full_Feature_word)):
                if word == self.Full_Feature_word[row]:
                    return self.Common_matrix[row]
                

                
                '''
                self.Fulltext_cut_content   初始化参数（切词后的嵌套列表 [[文章1切词结果]，[文章2切词结果]...]）
                Full_familiar_Feature = {}  # 储存特征和权重，为dict格式
                self.Full_Feature_word  特征词列表
                self.Common_matrix 共词矩阵
                '''

In [99]:
if __name__=="__main__":
    Fulltext_cut_content=seg_r
    Coword_one=Coword_matrix(Fulltext_cut_content) #对该类传入初始化参数
    print('=========================特征词===========================')
    print(Coword_one.get_Full_Feature_word())
    print('========================共词矩阵===========================')
    print(Coword_one.get_Common_matrix())
    print('===============“创业”词与所有特征词的关系程度===============')
    print(Coword_one.return_word_row("创业"))

=========================特征词===========================
['青年', '创业', '农村', '团委', '培训']
========================共词矩阵===========================
[6. 1. 3. 1. 0.]
[1. 3. 0. 0. 0.]
[3. 0. 3. 0. 0.]
[1. 0. 0. 2. 0.]
[0. 0. 0. 0. 2.]
None
===============“创业”词与所有特征词的关系程度===============
[1. 3. 0. 0. 0.]
